linters-settings:
  goimports:
    local-prefixes: github.com/kudelskisecurity/crystals-go

linters:
  disable-all: true

  # highly recommended:
  #  - revive # many exported functions and fields need documentation
  #  - errcheck # error return values are not checked; Misses API rework (error return values)
  #  - gosec # same as errcheck, plus Potential file inclusion via variable

  enable:
    - asciicheck
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - wrapcheck

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue

  exclude:
    - ST1000 # at least one file in a package should have a package comment; Excluded because is a TODO
