linters-settings:
  goimports:
    local-prefixes: github.com/kudelskisecurity/crystals-go

linters:
  disable-all: true
  # pending (either enable and handle, or deliberately drop):
  #  - errcheck
  #  - gocritic
  #  - gosec
  #  - ifshort
  #  - paralleltest
  #  - predeclared
  #  - revive
  #  - stylecheck
  #  - testpackage
  #  - thelper
  #  - unconvert
  enable:
    - asciicheck
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gochecknoinits
    - goconst
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - tagliatelle
    - tparallel
    - typecheck
    - unparam
    - unused
    - varcheck
    - wastedassign
    - wrapcheck

issues:
  exclude-use-default: false # disable filtering of defaults for better zero-issue policy
  max-per-linter: 0 # disable limit; report all issues of a linter
  max-same-issues: 0 # disable limit; report all issues of the same issue
